package cleanbank.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillResult generated by hbm2java
 */
@Entity
@Table(name = "BILL_RESULT", catalog = "cleanbank")
public class BillResult implements java.io.Serializable {

	private Integer id;
	private String moid;
	private String mbCd;
	private String price;
	private String resultmsg;
	private String cardauthcode;
	private String pgauthdate;
	private String pgauthtime;
	private String tid;
	private Date regDt;

	public BillResult() {
	}

	public BillResult(String moid, String mbCd, String price) {
		this.moid = moid;
		this.mbCd = mbCd;
		this.price = price;
	}

	public BillResult(String moid, String mbCd, String price, String resultmsg, String cardauthcode, String pgauthdate,
			String pgauthtime, String tid, Date regDt) {
		this.moid = moid;
		this.mbCd = mbCd;
		this.price = price;
		this.resultmsg = resultmsg;
		this.cardauthcode = cardauthcode;
		this.pgauthdate = pgauthdate;
		this.pgauthtime = pgauthtime;
		this.tid = tid;
		this.regDt = regDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "MOID", nullable = false, length = 45)
	public String getMoid() {
		return this.moid;
	}

	public void setMoid(String moid) {
		this.moid = moid;
	}

	@Column(name = "MB_CD", nullable = false, length = 45)
	public String getMbCd() {
		return this.mbCd;
	}

	public void setMbCd(String mbCd) {
		this.mbCd = mbCd;
	}

	@Column(name = "PRICE", nullable = false, length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "RESULTMSG", length = 500)
	public String getResultmsg() {
		return this.resultmsg;
	}

	public void setResultmsg(String resultmsg) {
		this.resultmsg = resultmsg;
	}

	@Column(name = "CARDAUTHCODE", length = 500)
	public String getCardauthcode() {
		return this.cardauthcode;
	}

	public void setCardauthcode(String cardauthcode) {
		this.cardauthcode = cardauthcode;
	}

	@Column(name = "PGAUTHDATE", length = 20)
	public String getPgauthdate() {
		return this.pgauthdate;
	}

	public void setPgauthdate(String pgauthdate) {
		this.pgauthdate = pgauthdate;
	}

	@Column(name = "PGAUTHTIME", length = 20)
	public String getPgauthtime() {
		return this.pgauthtime;
	}

	public void setPgauthtime(String pgauthtime) {
		this.pgauthtime = pgauthtime;
	}

	@Column(name = "TID", length = 100)
	public String getTid() {
		return this.tid;
	}

	public void setTid(String tid) {
		this.tid = tid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REG_DT", length = 19)
	public Date getRegDt() {
		return this.regDt;
	}

	public void setRegDt(Date regDt) {
		this.regDt = regDt;
	}

}
