package cleanbank.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.springframework.util.StringUtils;

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbAddress generated by hbm2java
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "TB_ADDRESS", catalog = "cleanbank")
public class TbAddress implements java.io.Serializable {

	private Integer id;

	@JsonIgnore
	private int adCd;

	@JsonIgnore
	private String delYn;

	@JsonIgnore
	private String evtNm;

	@JsonIgnore
	private Date regiDt;

	@JsonIgnore
	private String user;

	private String mbAddr1;
	private String mbAddr2;
	private int mbCd;
	private String mbLat;
	private String mbLng;
	public TbAddress() {
	}

	public TbAddress(int adCd, int mbCd) {
		this.adCd = adCd;
		this.mbCd = mbCd;
	}

	public TbAddress(int adCd, String delYn, String evtNm, String mbAddr1, String mbAddr2, int mbCd, String mbLat,
					 String mbLng, Date regiDt, String user) {
		this.adCd = adCd;
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.mbAddr1 = mbAddr1;
		this.mbAddr2 = mbAddr2;
		this.mbCd = mbCd;
		this.mbLat = mbLat;
		this.mbLng = mbLng;
		this.regiDt = regiDt;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "AD_CD", nullable = false)
	public int getAdCd() {
		return this.adCd;
	}

	public void setAdCd(int adCd) {
		this.adCd = adCd;
	}

	@Column(name = "DEL_YN", length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "MB_ADDR1", length = 100)
	public String getMbAddr1() {
		return this.mbAddr1;
	}

	public void setMbAddr1(String mbAddr1) {
		this.mbAddr1 = mbAddr1;
	}

	@Column(name = "MB_ADDR2", length = 100)
	public String getMbAddr2() {
		return this.mbAddr2;
	}

	public void setMbAddr2(String mbAddr2) {
		this.mbAddr2 = mbAddr2;
	}

	@Column(name = "MB_CD", nullable = false)
	public int getMbCd() {
		return this.mbCd;
	}

	public void setMbCd(int mbCd) {
		this.mbCd = mbCd;
	}

	@Column(name = "MB_LAT", length = 20)
	public String getMbLat() {
		return this.mbLat;
	}

	public void setMbLat(String mbLat) {
		this.mbLat = mbLat;
	}

	@Column(name = "MB_LNG", length = 20)
	public String getMbLng() {
		return this.mbLng;
	}

	public void setMbLng(String mbLng) {
		this.mbLng = mbLng;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	//	이하 수정 혹은 추가 ------------------------------------------------------------------------
	private String mode;

	//	신규/수정
	@JsonIgnore
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	//	주소1 + 주소2
	private String mbAddr;

	@Transient
	public String getMbAddr() {
		if(!StringUtils.hasText(this.mbAddr)) {
			if (StringUtils.hasText(this.mbAddr1)) {
				this.mbAddr = this.mbAddr1;

				if (StringUtils.hasText(this.mbAddr2)) {
					this.mbAddr += " "+ this.mbAddr2;
				}
			}
		}
		return mbAddr;
	}

	public void setMbAddr(String mbAddr) {
		this.mbAddr = mbAddr;
	}
}