package cleanbank.domain;

import javax.persistence.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbBranch generated by hbm2java
 */
@Entity
@Table(name = "TB_BRANCH", catalog = "cleanbank")
public class TbBranch implements java.io.Serializable {

	private Integer bnCd;
	private String bnBarCd;
	private String bnCeo;
	private Date bnCloseTm;
	private Integer bnDeliTm;
	private String bnFax;
	private String bnFri;
	private String bnMon;
	private String bnNm;
	private Date bnOpenTm;
	private Integer bnPer;
	private String bnSat;
	private String bnSun;
	private String bnTel;
	private String bnThu;
	private Integer bnTransTm;
	private String bnTue;
	private String bnWed;
	private String delYn;
	private String evtNm;
	private Integer ptCd;
	private Date regiDt;
	private String user;
	private Integer bnMonTo;
	private Integer bnTueTo;
	private Integer bnWedTo;
	private Integer bnThuTo;
	private Integer bnFriTo;
	private Integer bnSatTo;
	private Integer bnSunTo;

	public TbBranch() {
	}

	public TbBranch(String bnCeo, String bnNm, String bnTel, String delYn, Date regiDt, String user) {
		this.bnCeo = bnCeo;
		this.bnNm = bnNm;
		this.bnTel = bnTel;
		this.delYn = delYn;
		this.regiDt = regiDt;
		this.user = user;
	}

	public TbBranch(String bnBarCd, String bnCeo, Date bnCloseTm, Integer bnDeliTm, String bnFax, String bnFri,
					String bnMon, String bnNm, Date bnOpenTm, Integer bnPer, String bnSat, String bnSun, String bnTel,
					String bnThu, Integer bnTransTm, String bnTue, String bnWed, String delYn, String evtNm, Integer ptCd,
					Date regiDt, String user, Integer bnMonTo, Integer bnTueTo, Integer bnWedTo, Integer bnThuTo,
					Integer bnFriTo, Integer bnSatTo, Integer bnSunTo) {
		this.bnBarCd = bnBarCd;
		this.bnCeo = bnCeo;
		this.bnCloseTm = bnCloseTm;
		this.bnDeliTm = bnDeliTm;
		this.bnFax = bnFax;
		this.bnFri = bnFri;
		this.bnMon = bnMon;
		this.bnNm = bnNm;
		this.bnOpenTm = bnOpenTm;
		this.bnPer = bnPer;
		this.bnSat = bnSat;
		this.bnSun = bnSun;
		this.bnTel = bnTel;
		this.bnThu = bnThu;
		this.bnTransTm = bnTransTm;
		this.bnTue = bnTue;
		this.bnWed = bnWed;
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.ptCd = ptCd;
		this.regiDt = regiDt;
		this.user = user;
		this.bnMonTo = bnMonTo;
		this.bnTueTo = bnTueTo;
		this.bnWedTo = bnWedTo;
		this.bnThuTo = bnThuTo;
		this.bnFriTo = bnFriTo;
		this.bnSatTo = bnSatTo;
		this.bnSunTo = bnSunTo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BN_CD", unique = true, nullable = false)
	public Integer getBnCd() {
		return this.bnCd;
	}

	public void setBnCd(Integer bnCd) {
		this.bnCd = bnCd;
	}

	@Column(name = "BN_BAR_CD", length = 20)
	public String getBnBarCd() {
		return this.bnBarCd;
	}

	public void setBnBarCd(String bnBarCd) {
		this.bnBarCd = bnBarCd;
	}

	@Column(name = "BN_CEO", nullable = false, length = 20)
	public String getBnCeo() {
		return this.bnCeo;
	}

	public void setBnCeo(String bnCeo) {
		this.bnCeo = bnCeo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "BN_CLOSE_TM", length = 8)
	public Date getBnCloseTm() {
		return this.bnCloseTm;
	}

	public void setBnCloseTm(Date bnCloseTm) {
		this.bnCloseTm = bnCloseTm;
	}

	@Column(name = "BN_DELI_TM")
	public Integer getBnDeliTm() {
		return this.bnDeliTm;
	}

	public void setBnDeliTm(Integer bnDeliTm) {
		this.bnDeliTm = bnDeliTm;
	}

	@Column(name = "BN_FAX", length = 20)
	public String getBnFax() {
		return this.bnFax;
	}

	public void setBnFax(String bnFax) {
		this.bnFax = bnFax;
	}

	@Column(name = "BN_FRI", length = 1)
	public String getBnFri() {
		return this.bnFri;
	}

	public void setBnFri(String bnFri) {
		this.bnFri = bnFri;
	}

	@Column(name = "BN_MON", length = 1)
	public String getBnMon() {
		return this.bnMon;
	}

	public void setBnMon(String bnMon) {
		this.bnMon = bnMon;
	}

	@Column(name = "BN_NM", nullable = false, length = 50)
	public String getBnNm() {
		return this.bnNm;
	}

	public void setBnNm(String bnNm) {
		this.bnNm = bnNm;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "BN_OPEN_TM", length = 8)
	public Date getBnOpenTm() {
		return this.bnOpenTm;
	}

	public void setBnOpenTm(Date bnOpenTm) {
		this.bnOpenTm = bnOpenTm;
	}

	@Column(name = "BN_PER")
	public Integer getBnPer() {
		return this.bnPer;
	}

	public void setBnPer(Integer bnPer) {
		this.bnPer = bnPer;
	}

	@Column(name = "BN_SAT", length = 1)
	public String getBnSat() {
		return this.bnSat;
	}

	public void setBnSat(String bnSat) {
		this.bnSat = bnSat;
	}

	@Column(name = "BN_SUN", length = 1)
	public String getBnSun() {
		return this.bnSun;
	}

	public void setBnSun(String bnSun) {
		this.bnSun = bnSun;
	}

	@Column(name = "BN_TEL", nullable = false, length = 20)
	public String getBnTel() {
		return this.bnTel;
	}

	public void setBnTel(String bnTel) {
		this.bnTel = bnTel;
	}

	@Column(name = "BN_THU", length = 1)
	public String getBnThu() {
		return this.bnThu;
	}

	public void setBnThu(String bnThu) {
		this.bnThu = bnThu;
	}

	@Column(name = "BN_TRANS_TM")
	public Integer getBnTransTm() {
		return this.bnTransTm;
	}

	public void setBnTransTm(Integer bnTransTm) {
		this.bnTransTm = bnTransTm;
	}

	@Column(name = "BN_TUE", length = 1)
	public String getBnTue() {
		return this.bnTue;
	}

	public void setBnTue(String bnTue) {
		this.bnTue = bnTue;
	}

	@Column(name = "BN_WED", length = 1)
	public String getBnWed() {
		return this.bnWed;
	}

	public void setBnWed(String bnWed) {
		this.bnWed = bnWed;
	}

	@Column(name = "DEL_YN", nullable = false, length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "PT_CD")
	public Integer getPtCd() {
		return this.ptCd;
	}

	public void setPtCd(Integer ptCd) {
		this.ptCd = ptCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", nullable = false, length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", nullable = false, length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "BN_MON_TO")
	public Integer getBnMonTo() {
		return this.bnMonTo;
	}

	public void setBnMonTo(Integer bnMonTo) {
		this.bnMonTo = bnMonTo;
	}

	@Column(name = "BN_TUE_TO")
	public Integer getBnTueTo() {
		return this.bnTueTo;
	}

	public void setBnTueTo(Integer bnTueTo) {
		this.bnTueTo = bnTueTo;
	}

	@Column(name = "BN_WED_TO")
	public Integer getBnWedTo() {
		return this.bnWedTo;
	}

	public void setBnWedTo(Integer bnWedTo) {
		this.bnWedTo = bnWedTo;
	}

	@Column(name = "BN_THU_TO")
	public Integer getBnThuTo() {
		return this.bnThuTo;
	}

	public void setBnThuTo(Integer bnThuTo) {
		this.bnThuTo = bnThuTo;
	}

	@Column(name = "BN_FRI_TO")
	public Integer getBnFriTo() {
		return this.bnFriTo;
	}

	public void setBnFriTo(Integer bnFriTo) {
		this.bnFriTo = bnFriTo;
	}

	@Column(name = "BN_SAT_TO")
	public Integer getBnSatTo() {
		return this.bnSatTo;
	}

	public void setBnSatTo(Integer bnSatTo) {
		this.bnSatTo = bnSatTo;
	}

	@Column(name = "BN_SUN_TO")
	public Integer getBnSunTo() {
		return this.bnSunTo;
	}

	public void setBnSunTo(Integer bnSunTo) {
		this.bnSunTo = bnSunTo;
	}

	//	이하 수정 혹은 추가 ------------------------------------------------------------------------
	private String mode;

	//	신규/수정
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	/*public Date getBnOpenTm() {
		return this.bnOpenTm;
	}*/

	//	영업시작시간
	private String bnOpenTm0;

	@Transient
	public String getbnOpenTm0() {
		String tempDate = this.bnOpenTm0;

		if(this.bnOpenTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("HH:mm");
			tempDate = sdFormat.format(this.bnOpenTm);
		}

		return tempDate;
	}

	//	영업종료시간
	private String bnCloseTm0;

	@Transient
	public String getbnCloseTm0() {
		String tempDate = this.bnCloseTm0;

		if(this.bnCloseTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("HH:mm");
			tempDate = sdFormat.format(this.bnCloseTm);
		}

		return tempDate;
	}

	public void setbnCloseTm0(String bnCloseTm0) {
		this.bnCloseTm0 = bnCloseTm0;
	}

	public void setbnOpenTm0(String bnOpenTm0) {
		this.bnOpenTm0 = bnOpenTm0;
	}

//	영업시작시간(시)
	private String bnOpenTm1;

	@Transient
	public String getBnOpenTm1() {
		String tempDate = this.bnOpenTm1;

		if(this.bnOpenTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("HH");
			tempDate = sdFormat.format(this.bnOpenTm);
		}

		return tempDate;
	}

	public void setBnOpenTm1(String bnOpenTm1) {
		this.bnOpenTm1 = bnOpenTm1;
	}

//	영업시작시간(분)
	private String bnOpenTm2;

	@Transient
	public String getBnOpenTm2() {
		String tempDate = this.bnOpenTm2;

		if(this.bnOpenTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("mm");
			tempDate = sdFormat.format(this.bnOpenTm);
		}

		return tempDate;
	}

	public void setBnOpenTm2(String bnOpenTm2) {
		this.bnOpenTm2 = bnOpenTm2;
	}

	//	영업종료시간(시)
	private String bnCloseTm1;

	@Transient
	public String getBnCloseTm1() {
		String tempDate = this.bnCloseTm1;

		if(this.bnCloseTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("HH");
			tempDate = sdFormat.format(this.bnCloseTm);
		}

		return tempDate;
	}

	public void setBnCloseTm1(String bnCloseTm1) {
		this.bnCloseTm1 = bnCloseTm1;
	}

	//	영업종료시간(분)
	private String bnCloseTm2;

	@Transient
	public String getBnCloseTm2() {
		String tempDate = this.bnCloseTm2;

		if(this.bnCloseTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("mm");
			tempDate = sdFormat.format(this.bnCloseTm);
		}

		return tempDate;
	}

	public void setBnCloseTm2(String bnCloseTm2) {
		this.bnCloseTm2 = bnCloseTm2;
	}

}