package cleanbank.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbCode generated by hbm2java
 */
@Entity
@Table(name = "TB_CODE", catalog = "cleanbank")
public class TbCode implements java.io.Serializable {

	private Integer id;
	private String cdGp;
	private String cdIt;
	private String cdNm;
	private Integer cdSort;
	private String delYn;
	private String evtNm;
	private Date regiDt;
	private String user;

	public TbCode() {
	}

	public TbCode(String cdGp, String cdIt, String cdNm, Date regiDt, String user) {
		this.cdGp = cdGp;
		this.cdIt = cdIt;
		this.cdNm = cdNm;
		this.regiDt = regiDt;
		this.user = user;
	}

	public TbCode(String cdGp, String cdIt, String cdNm, Integer cdSort, String delYn, String evtNm, Date regiDt,
				  String user) {
		this.cdGp = cdGp;
		this.cdIt = cdIt;
		this.cdNm = cdNm;
		this.cdSort = cdSort;
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.regiDt = regiDt;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CD_GP", nullable = false, length = 2)
	public String getCdGp() {
		return this.cdGp;
	}

	public void setCdGp(String cdGp) {
		this.cdGp = cdGp;
	}

	@Column(name = "CD_IT", nullable = false, length = 2)
	public String getCdIt() {
		return this.cdIt;
	}

	public void setCdIt(String cdIt) {
		this.cdIt = cdIt;
	}

	@Column(name = "CD_NM", nullable = false, length = 20)
	public String getCdNm() {
		return this.cdNm;
	}

	public void setCdNm(String cdNm) {
		this.cdNm = cdNm;
	}

	@Column(name = "CD_SORT")
	public Integer getCdSort() {
		return this.cdSort;
	}

	public void setCdSort(Integer cdSort) {
		this.cdSort = cdSort;
	}

	@Column(name = "DEL_YN", length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	//	http://stackoverflow.com/questions/12463049/date-format-mapping-to-json-jackson
//	https://www.lesstif.com/pages/viewpage.action?pageId=24445204
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", nullable = false, length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", nullable = false, length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	//	이하 추가
	private String mode;
	private String newPass;

	//	신규/수정
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}
}