package cleanbank.domain;

import javax.persistence.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbEmployee generated by hbm2java
 */
@Entity
@Table(name = "TB_EMPLOYEE", catalog = "cleanbank", uniqueConstraints = @UniqueConstraint(columnNames = "EP_EMAIL") )
public class TbEmployee implements java.io.Serializable {

	private Integer epCd;
	private Integer bnCd;
	private String delYn;
	private String epDriveYn;
	private String epEmail;
	private String epImg;
	private String epIntro;
	private Date epJoinDt;
	private String epLevel;
	private String epLoc;
	private String epNm;
	private String epPart;
	private String epPass;
	private String epSex;
	private String epTel;
	private String evtNm;
	private Date regiDt;
	private String user;
	private String epDeviceToken;

	public TbEmployee() {
	}

	public TbEmployee(Integer bnCd, String delYn, String epDriveYn, String epEmail, String epImg, String epIntro,
					  Date epJoinDt, String epLevel, String epLoc, String epNm, String epPart, String epPass, String epSex,
					  String epTel, String evtNm, Date regiDt, String user, String epDeviceToken) {
		this.bnCd = bnCd;
		this.delYn = delYn;
		this.epDriveYn = epDriveYn;
		this.epEmail = epEmail;
		this.epImg = epImg;
		this.epIntro = epIntro;
		this.epJoinDt = epJoinDt;
		this.epLevel = epLevel;
		this.epLoc = epLoc;
		this.epNm = epNm;
		this.epPart = epPart;
		this.epPass = epPass;
		this.epSex = epSex;
		this.epTel = epTel;
		this.evtNm = evtNm;
		this.regiDt = regiDt;
		this.user = user;
		this.epDeviceToken = epDeviceToken;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EP_CD", unique = true, nullable = false)
	public Integer getEpCd() {
		return this.epCd;
	}

	public void setEpCd(Integer epCd) {
		this.epCd = epCd;
	}

	@Column(name = "BN_CD")
	public Integer getBnCd() {
		return this.bnCd;
	}

	public void setBnCd(Integer bnCd) {
		this.bnCd = bnCd;
	}

	@Column(name = "DEL_YN", length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EP_DRIVE_YN", length = 4)
	public String getEpDriveYn() {
		return this.epDriveYn;
	}

	public void setEpDriveYn(String epDriveYn) {
		this.epDriveYn = epDriveYn;
	}

	@Column(name = "EP_EMAIL", unique = true, length = 100)
	public String getEpEmail() {
		return this.epEmail;
	}

	public void setEpEmail(String epEmail) {
		this.epEmail = epEmail;
	}

	@Column(name = "EP_IMG", length = 100)
	public String getEpImg() {
		return this.epImg;
	}

	public void setEpImg(String epImg) {
		this.epImg = epImg;
	}

	@Column(name = "EP_INTRO", length = 4000)
	public String getEpIntro() {
		return this.epIntro;
	}

	public void setEpIntro(String epIntro) {
		this.epIntro = epIntro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EP_JOIN_DT", length = 19)
	public Date getEpJoinDt() {
		return this.epJoinDt;
	}

	public void setEpJoinDt(Date epJoinDt) {
		this.epJoinDt = epJoinDt;
	}

	@Column(name = "EP_LEVEL", length = 4)
	public String getEpLevel() {
		return this.epLevel;
	}

	public void setEpLevel(String epLevel) {
		this.epLevel = epLevel;
	}

	@Column(name = "EP_LOC", length = 6)
	public String getEpLoc() {
		return this.epLoc;
	}

	public void setEpLoc(String epLoc) {
		this.epLoc = epLoc;
	}

	@Column(name = "EP_NM", length = 20)
	public String getEpNm() {
		return this.epNm;
	}

	public void setEpNm(String epNm) {
		this.epNm = epNm;
	}

	@Column(name = "EP_PART", length = 4)
	public String getEpPart() {
		return this.epPart;
	}

	public void setEpPart(String epPart) {
		this.epPart = epPart;
	}

	@Column(name = "EP_PASS", length = 100)
	public String getEpPass() {
		return this.epPass;
	}

	public void setEpPass(String epPass) {
		this.epPass = epPass;
	}

	@Column(name = "EP_SEX", length = 4)
	public String getEpSex() {
		return this.epSex;
	}

	public void setEpSex(String epSex) {
		this.epSex = epSex;
	}

	@Column(name = "EP_TEL", length = 50)
	public String getEpTel() {
		return this.epTel;
	}

	public void setEpTel(String epTel) {
		this.epTel = epTel;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "EP_DEVICE_TOKEN", length = 200)
	public String getEpDeviceToken() {
		return this.epDeviceToken;
	}

	public void setEpDeviceToken(String epDeviceToken) {
		this.epDeviceToken = epDeviceToken;
	}

	//	이하 추가
	private String mode;
	private String newPass;
	private String curPass;

	//	수정시 비밀번호 변경
	@Transient
	public String getNewPass() {
		return newPass;
	}

//코디앱에서 비밀번호 수정시 확인용
	public void setNewPass(String newPass) {
		this.newPass = newPass;
	}

	@Transient
	public String getCurPass() {
		return curPass;
	}

	public void setCurPass(String curPass) {
		this.curPass = curPass;
	}

	//	신규/수정
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	//	가입일자
//	TODO : @JsonFormat(pattern="yyyy-MM-dd") 으로 지정하면 된다!!!
//	http://blog.kaczmarzyk.net/2014/03/23/alternative-api-for-filtering-data-with-spring-mvc-and-spring-data/
	@Transient
	public String getRegiDt2() {
		String tempDate = null;

		if(this.regiDt != null) {
			DateFormat sdFormat = new SimpleDateFormat("yyyy-MM-dd");
			tempDate = sdFormat.format(this.regiDt);
		}

		return tempDate;
	}

//	입사일자 : 엑셀에서 사용?
	@Transient
	public String getEpJoinDt2() {
		String tempDate = null;

		if(this.epJoinDt != null) {
			DateFormat sdFormat = new SimpleDateFormat("yyyy-MM-dd");
			tempDate = sdFormat.format(this.epJoinDt);
		}

		return tempDate;
	}

}