package cleanbank.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbLocation generated by hbm2java
 */
@Entity
@Table(name = "TB_LOCATION", catalog = "cleanbank")
public class TbLocation implements java.io.Serializable {

	private Integer id;
	private String delYn;
	private String evtNm;
	private String loc1;
	private String loc2;
	private String loc3;
	private String name;
	private Date regiDt;
	private String user;
	private Integer sortOrder;
	private String loDesc;

	public TbLocation() {
	}

	public TbLocation(String delYn, String evtNm, String loc1, String loc2, String loc3, String name, Date regiDt,
					  String user, Integer sortOrder, String loDesc) {
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.loc1 = loc1;
		this.loc2 = loc2;
		this.loc3 = loc3;
		this.name = name;
		this.regiDt = regiDt;
		this.user = user;
		this.sortOrder = sortOrder;
		this.loDesc = loDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "DEL_YN")
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM")
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "LOC1")
	public String getLoc1() {
		return this.loc1;
	}

	public void setLoc1(String loc1) {
		this.loc1 = loc1;
	}

	@Column(name = "LOC2")
	public String getLoc2() {
		return this.loc2;
	}

	public void setLoc2(String loc2) {
		this.loc2 = loc2;
	}

	@Column(name = "LOC3")
	public String getLoc3() {
		return this.loc3;
	}

	public void setLoc3(String loc3) {
		this.loc3 = loc3;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER")
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "SORT_ORDER")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "LO_DESC", length = 200)
	public String getLoDesc() {
		return this.loDesc;
	}

	public void setLoDesc(String loDesc) {
		this.loDesc = loDesc;
	}

	//	이하 수정 혹은 추가 ------------------------------------------------------------------------

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	private String mode;

	//	신규/수정
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}
}
