package cleanbank.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.data.rest.core.annotation.RestResource;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbMember generated by hbm2java
 */
@Entity
@Table(name = "TB_MEMBER", catalog = "cleanbank")
public class TbMember implements java.io.Serializable {

	private Integer mbCd;
	private Integer bnCd;
	private String delYn;
	private String evtNm;
	private String mbAnimal;
	private Date mbBirth;
	private String mbEmail;
	private String mbHabi;
	private Date mbJoinDt;
	private String mbKid;
	private String mbLevel;
	private String mbMarri;
	private String mbNicNm;
	private String mbNm;
	private String mbPath;
	private String mbPush;
	private String mbSms;
	private String mbStatus;
	private String mbTel;
	private Date regiDt;
	private String user;
	private String mbMycode;
	private String mbSucode;
	private String mbDeviceToken;
	private String mbBillkey;
	private String mbBillinfo;
	private Integer mbPoint;
	private String mbPushToken;

	public TbMember() {
	}

	public TbMember(String mbEmail) {
		this.mbEmail = mbEmail;
	}

	public TbMember(Integer bnCd, String delYn, String evtNm, String mbAnimal, Date mbBirth, String mbEmail,
					String mbHabi, Date mbJoinDt, String mbKid, String mbLevel, String mbMarri, String mbNicNm, String mbNm,
					String mbPass, String mbPath, String mbPush, String mbSms, String mbStatus, String mbTel, Date regiDt,
					String user, String mbMycode, String mbSucode, String mbDeviceToken, String mbBillkey, String mbBillinfo,
					Integer mbPoint, String mbPushToken) {
		this.bnCd = bnCd;
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.mbAnimal = mbAnimal;
		this.mbBirth = mbBirth;
		this.mbEmail = mbEmail;
		this.mbHabi = mbHabi;
		this.mbJoinDt = mbJoinDt;
		this.mbKid = mbKid;
		this.mbLevel = mbLevel;
		this.mbMarri = mbMarri;
		this.mbNicNm = mbNicNm;
		this.mbNm = mbNm;
		this.mbPass = mbPass;
		this.mbPath = mbPath;
		this.mbPush = mbPush;
		this.mbSms = mbSms;
		this.mbStatus = mbStatus;
		this.mbTel = mbTel;
		this.regiDt = regiDt;
		this.user = user;
		this.mbMycode = mbMycode;
		this.mbSucode = mbSucode;
		this.mbDeviceToken = mbDeviceToken;
		this.mbBillkey = mbBillkey;
		this.mbBillinfo = mbBillinfo;
		this.mbPoint = mbPoint;
		this.mbPushToken = mbPushToken;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MB_CD", unique = true, nullable = false)
	public Integer getMbCd() {
		return this.mbCd;
	}

	public void setMbCd(Integer mbCd) {
		this.mbCd = mbCd;
	}

	@Column(name = "BN_CD")
	public Integer getBnCd() {
		return this.bnCd;
	}

	public void setBnCd(Integer bnCd) {
		this.bnCd = bnCd;
	}

	@Column(name = "DEL_YN", length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "MB_ANIMAL", length = 1)
	public String getMbAnimal() {
		return this.mbAnimal;
	}

	public void setMbAnimal(String mbAnimal) {
		this.mbAnimal = mbAnimal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MB_BIRTH", length = 19)
	public Date getMbBirth() {
		return this.mbBirth;
	}

	public void setMbBirth(Date mbBirth) {
		this.mbBirth = mbBirth;
	}

	@Column(name = "MB_EMAIL", nullable = false, length = 200)
	public String getMbEmail() {
		return this.mbEmail;
	}

	public void setMbEmail(String mbEmail) {
		this.mbEmail = mbEmail;
	}

	@Column(name = "MB_HABI", length = 50)
	public String getMbHabi() {
		return this.mbHabi;
	}

	public void setMbHabi(String mbHabi) {
		this.mbHabi = mbHabi;
	}

	public void setMbJoinDt(Date mbJoinDt) {
		this.mbJoinDt = mbJoinDt;
	}

	@Column(name = "MB_KID", length = 1)
	public String getMbKid() {
		return this.mbKid;
	}

	public void setMbKid(String mbKid) {
		this.mbKid = mbKid;
	}

	@Column(name = "MB_LEVEL", length = 4)
	public String getMbLevel() {
		return this.mbLevel;
	}

	public void setMbLevel(String mbLevel) {
		this.mbLevel = mbLevel;
	}

	@Column(name = "MB_MARRI", length = 1)
	public String getMbMarri() {
		return this.mbMarri;
	}

	public void setMbMarri(String mbMarri) {
		this.mbMarri = mbMarri;
	}

	@Column(name = "MB_NIC_NM", length = 100)
	public String getMbNicNm() {
		return this.mbNicNm;
	}

	public void setMbNicNm(String mbNicNm) {
		this.mbNicNm = mbNicNm;
	}

	@Column(name = "MB_NM", length = 30)
	public String getMbNm() {
		return this.mbNm;
	}

	public void setMbNm(String mbNm) {
		this.mbNm = mbNm;
	}

	@Column(name = "MB_PASS", length = 20)
	public String getMbPass() {
		return this.mbPass;
	}

	public void setMbPass(String mbPass) {
		this.mbPass = mbPass;
	}

	@Column(name = "MB_PATH", length = 10)
	public String getMbPath() {
		return this.mbPath;
	}

	public void setMbPath(String mbPath) {
		this.mbPath = mbPath;
	}

	@Column(name = "MB_PUSH", length = 1)
	public String getMbPush() {
		return this.mbPush;
	}

	public void setMbPush(String mbPush) {
		this.mbPush = mbPush;
	}

	@Column(name = "MB_SMS", length = 1)
	public String getMbSms() {
		return this.mbSms;
	}

	public void setMbSms(String mbSms) {
		this.mbSms = mbSms;
	}

	@Column(name = "MB_STATUS", length = 4)
	public String getMbStatus() {
		return this.mbStatus;
	}

	public void setMbStatus(String mbStatus) {
		this.mbStatus = mbStatus;
	}

	@Column(name = "MB_TEL", length = 20)
	public String getMbTel() {
		return this.mbTel;
	}

	public void setMbTel(String mbTel) {
		this.mbTel = mbTel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "MB_MYCODE", length = 100)
	public String getMbMycode() {
		return this.mbMycode;
	}

	public void setMbMycode(String mbMycode) {
		this.mbMycode = mbMycode;
	}

	@Column(name = "MB_SUCODE", length = 100)
	public String getMbSucode() {
		return this.mbSucode;
	}

	public void setMbSucode(String mbSucode) {
		this.mbSucode = mbSucode;
	}

	@Column(name = "MB_DEVICE_TOKEN", length = 200)
	public String getMbDeviceToken() {
		return this.mbDeviceToken;
	}

	public void setMbDeviceToken(String mbDeviceToken) {
		this.mbDeviceToken = mbDeviceToken;
	}

	@Column(name = "MB_BILLKEY", length = 100)
	public String getMbBillkey() {
		return this.mbBillkey;
	}

	public void setMbBillkey(String mbBillkey) {
		this.mbBillkey = mbBillkey;
	}

	@Column(name = "MB_BILLINFO", length = 100)
	public String getMbBillinfo() {
		return this.mbBillinfo;
	}

	public void setMbBillinfo(String mbBillinfo) {
		this.mbBillinfo = mbBillinfo;
	}

	@Column(name = "MB_POINT")
	public Integer getMbPoint() {
		return this.mbPoint;
	}

	public void setMbPoint(Integer mbPoint) {
		this.mbPoint = mbPoint;
	}

	@Column(name = "MB_PUSH_TOKEN", length = 200)
	public String getMbPushToken() {
		return this.mbPushToken;
	}

	public void setMbPushToken(String mbPushToken) {
		this.mbPushToken = mbPushToken;
	}

	//	이하 수정 혹은 추가 ------------------------------------------------------------------------
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MB_JOIN_DT", length = 19)
	public Date getMbJoinDt() {
		return this.mbJoinDt;
	}

	//	입사일자 : 엑셀에서 사용?
	@RestResource(exported = false)
	@JsonIgnore
	@Transient
	public String getMbJoinDt2() {
		String tempDate = null;

		if(this.mbJoinDt != null) {
			DateFormat sdFormat = new SimpleDateFormat("yyyy-MM-dd");
			tempDate = sdFormat.format(this.mbJoinDt);
		}

		return tempDate;
	}

	@RestResource(exported = false)
	@JsonIgnore
	private String mode;

	//	신규/수정
	@RestResource(exported = false)
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

//	모바일 api용 주소/위도/경도 및 자동 로그인 처리 되었는지 여부(최초에만 Y)
	private String mbAddr1;
	private String mbAddr2;
	private String mbLat;
	private String mbLng;
	private String mbNewYn;

	@Transient
	public String getMbNewYn() {
		return mbNewYn;
	}

	public void setMbNewYn(String mbNewYn) {
		this.mbNewYn = mbNewYn;
	}

//	private String msg;

	@Transient
	public String getMbLng() {
		return mbLng;
	}

	public void setMbLng(String mbLng) {
		this.mbLng = mbLng;
	}

	@Transient
	public String getMbLat() {
		return mbLat;
	}

	public void setMbLat(String mbLat) {
		this.mbLat = mbLat;
	}

	@Transient
	public String getMbAddr2() {
		return mbAddr2;
	}

	public void setMbAddr2(String mbAddr2) {
		this.mbAddr2 = mbAddr2;
	}

	@Transient
	public String getMbAddr1() {
		return mbAddr1;
	}

	public void setMbAddr1(String mbAddr1) {
		this.mbAddr1 = mbAddr1;
	}

	@JsonIgnore
	private String mbPass;

	/*@Transient
	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}*/
}