package cleanbank.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.apache.commons.lang3.StringUtils;
import org.springframework.web.multipart.MultipartFile;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**evtNm
 * TbOrderItems generated by hbm2java
 */
@Entity
@Table(name = "TB_ORDER_ITEMS", catalog = "cleanbank")
public class TbOrderItems implements java.io.Serializable {

	private Long id;
	private String delYn;
	private String evtNm;
	private Integer itAddChg;
	private String itBrand;
	private long itCd;
	private String itClMemo;
	private String itClaim;
	private Date itClaimDt;
	private int itCnt;
	private String itColor;
	private String itDeliAddr;
	private Date itDeliFuVisitDt;
	private Date itDeliVisitDt;
	private Date itInDt;
	private String itMemo;
	private Date itOutDt;
	private String itPatten;
	private int itPrice;
	private String itRefund;
	private String itReqAddr;
	private Date itReqDt;
	private String itStatus;
	private String itTac;
	private Date itVisitDt;
	private long orCd;
	private String pdLvl1;
	private String pdLvl2;
	private String pdLvl3;
	private Date regiDt;
	private String user;
	private String itBeginTac;
	private Date itRegiDt;
	private String itRegiStaff;
	private Date itBaekInDt;
	private String itFactoryMemo;

	public TbOrderItems() {
	}

	public TbOrderItems(String delYn, long itCd, int itCnt, int itPrice, String itReqAddr, Date itReqDt,
						String itStatus, long orCd, String pdLvl1, String pdLvl2, String pdLvl3, Date regiDt, String user) {
		this.delYn = delYn;
		this.itCd = itCd;
		this.itCnt = itCnt;
		this.itPrice = itPrice;
		this.itReqAddr = itReqAddr;
		this.itReqDt = itReqDt;
		this.itStatus = itStatus;
		this.orCd = orCd;
		this.pdLvl1 = pdLvl1;
		this.pdLvl2 = pdLvl2;
		this.pdLvl3 = pdLvl3;
		this.regiDt = regiDt;
		this.user = user;
	}

	public TbOrderItems(String delYn, String evtNm, Integer itAddChg, String itBrand, long itCd, String itClMemo,
						String itClaim, Date itClaimDt, int itCnt, String itColor, String itDeliAddr, Date itDeliFuVisitDt,
						Date itDeliVisitDt, Date itInDt, String itMemo, Date itOutDt, String itPatten, int itPrice, String itRefund,
						String itReqAddr, Date itReqDt, String itStatus, String itTac, Date itVisitDt, long orCd, String pdLvl1,
						String pdLvl2, String pdLvl3, Date regiDt, String user, String itBeginTac, Date itRegiDt,
						String itRegiStaff, Date itBaekInDt, String itFactoryMemo) {
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.itAddChg = itAddChg;
		this.itBrand = itBrand;
		this.itCd = itCd;
		this.itClMemo = itClMemo;
		this.itClaim = itClaim;
		this.itClaimDt = itClaimDt;
		this.itCnt = itCnt;
		this.itColor = itColor;
		this.itDeliAddr = itDeliAddr;
		this.itDeliFuVisitDt = itDeliFuVisitDt;
		this.itDeliVisitDt = itDeliVisitDt;
		this.itInDt = itInDt;
		this.itMemo = itMemo;
		this.itOutDt = itOutDt;
		this.itPatten = itPatten;
		this.itPrice = itPrice;
		this.itRefund = itRefund;
		this.itReqAddr = itReqAddr;
		this.itReqDt = itReqDt;
		this.itStatus = itStatus;
		this.itTac = itTac;
		this.itVisitDt = itVisitDt;
		this.orCd = orCd;
		this.pdLvl1 = pdLvl1;
		this.pdLvl2 = pdLvl2;
		this.pdLvl3 = pdLvl3;
		this.regiDt = regiDt;
		this.user = user;
		this.itBeginTac = itBeginTac;
		this.itRegiDt = itRegiDt;
		this.itRegiStaff = itRegiStaff;
		this.itBaekInDt = itBaekInDt;
		this.itFactoryMemo = itFactoryMemo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "DEL_YN", nullable = false, length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "IT_ADD_CHG")
	public Integer getItAddChg() {
		return this.itAddChg;
	}

	public void setItAddChg(Integer itAddChg) {
		this.itAddChg = itAddChg;
	}

	@Column(name = "IT_BRAND", length = 100)
	public String getItBrand() {
		return this.itBrand;
	}

	public void setItBrand(String itBrand) {
		this.itBrand = itBrand;
	}

	@Column(name = "IT_CD", nullable = false)
	public long getItCd() {
		return this.itCd;
	}

	public void setItCd(long itCd) {
		this.itCd = itCd;
	}

	@Column(name = "IT_CL_MEMO", length = 500)
	public String getItClMemo() {
		return this.itClMemo;
	}

	public void setItClMemo(String itClMemo) {
		this.itClMemo = itClMemo;
	}

	@Column(name = "IT_CLAIM", length = 1)
	public String getItClaim() {
		return this.itClaim;
	}

	public void setItClaim(String itClaim) {
		this.itClaim = itClaim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_CLAIM_DT", length = 19)
	public Date getItClaimDt() {
		return this.itClaimDt;
	}

	public void setItClaimDt(Date itClaimDt) {
		this.itClaimDt = itClaimDt;
	}

	@Column(name = "IT_CNT", nullable = false)
	public int getItCnt() {
		return this.itCnt;
	}

	public void setItCnt(int itCnt) {
		this.itCnt = itCnt;
	}

	@Column(name = "IT_COLOR", length = 20)
	public String getItColor() {
		return this.itColor;
	}

	public void setItColor(String itColor) {
		this.itColor = itColor;
	}

	@Column(name = "IT_DELI_ADDR", length = 500)
	public String getItDeliAddr() {
		return this.itDeliAddr;
	}

	public void setItDeliAddr(String itDeliAddr) {
		this.itDeliAddr = itDeliAddr;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_DELI_FU_VISIT_DT", length = 19)
	public Date getItDeliFuVisitDt() {
		return this.itDeliFuVisitDt;
	}*/

	public void setItDeliFuVisitDt(Date itDeliFuVisitDt) {
		this.itDeliFuVisitDt = itDeliFuVisitDt;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_DELI_VISIT_DT", length = 19)
	public Date getItDeliVisitDt() {
		return this.itDeliVisitDt;
	}*/

	public void setItDeliVisitDt(Date itDeliVisitDt) {
		this.itDeliVisitDt = itDeliVisitDt;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_IN_DT", length = 19)
	public Date getItInDt() {
		return this.itInDt;
	}*/

	public void setItInDt(Date itInDt) {
		this.itInDt = itInDt;
	}

	@Column(name = "IT_MEMO", length = 4000)
	public String getItMemo() {
		return this.itMemo;
	}

	public void setItMemo(String itMemo) {
		this.itMemo = itMemo;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_OUT_DT", length = 19)
	public Date getItOutDt() {
		return this.itOutDt;
	}*/

	public void setItOutDt(Date itOutDt) {
		this.itOutDt = itOutDt;
	}

	@Column(name = "IT_PATTEN", length = 20)
	public String getItPatten() {
		return this.itPatten;
	}

	public void setItPatten(String itPatten) {
		this.itPatten = itPatten;
	}

	@Column(name = "IT_PRICE", nullable = false)
	public int getItPrice() {
		return this.itPrice;
	}

	public void setItPrice(int itPrice) {
		this.itPrice = itPrice;
	}

	@Column(name = "IT_REFUND", length = 4)
	public String getItRefund() {
		return this.itRefund;
	}

	public void setItRefund(String itRefund) {
		this.itRefund = itRefund;
	}

	@Column(name = "IT_REQ_ADDR", nullable = false, length = 500)
	public String getItReqAddr() {
		return this.itReqAddr;
	}

	public void setItReqAddr(String itReqAddr) {
		this.itReqAddr = itReqAddr;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_REQ_DT", nullable = false, length = 19)
	public Date getItReqDt() {
		return this.itReqDt;
	}*/

	public void setItReqDt(Date itReqDt) {
		this.itReqDt = itReqDt;
	}

	@Column(name = "IT_STATUS", nullable = false, length = 4)
	public String getItStatus() {
		return this.itStatus;
	}

	public void setItStatus(String itStatus) {
		this.itStatus = itStatus;
	}

	@Column(name = "IT_TAC", length = 20)
	public String getItTac() {
		return this.itTac;
	}

	public void setItTac(String itTac) {
		this.itTac = itTac;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_VISIT_DT", length = 19)
	public Date getItVisitDt() {
		return this.itVisitDt;
	}*/

	public void setItVisitDt(Date itVisitDt) {
		this.itVisitDt = itVisitDt;
	}

	@Column(name = "OR_CD", nullable = false)
	public long getOrCd() {
		return this.orCd;
	}

	public void setOrCd(long orCd) {
		this.orCd = orCd;
	}

	@Column(name = "PD_LVL1", nullable = false, length = 2)
	public String getPdLvl1() {
		return this.pdLvl1;
	}

	public void setPdLvl1(String pdLvl1) {
		this.pdLvl1 = pdLvl1;
	}

	@Column(name = "PD_LVL2", nullable = false, length = 2)
	public String getPdLvl2() {
		return this.pdLvl2;
	}

	public void setPdLvl2(String pdLvl2) {
		this.pdLvl2 = pdLvl2;
	}

	@Column(name = "PD_LVL3", nullable = false, length = 2)
	public String getPdLvl3() {
		return this.pdLvl3;
	}

	public void setPdLvl3(String pdLvl3) {
		this.pdLvl3 = pdLvl3;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", nullable = false, length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}*/

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", nullable = false, length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "IT_BEGIN_TAC", length = 7)
	public String getItBeginTac() {
		return this.itBeginTac;
	}

	public void setItBeginTac(String itBeginTac) {
		this.itBeginTac = itBeginTac;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_REGI_DT", length = 19)
	public Date getItRegiDt() {
		return this.itRegiDt;
	}

	public void setItRegiDt(Date itRegiDt) {
		this.itRegiDt = itRegiDt;
	}

	@Column(name = "IT_REGI_STAFF", length = 20)
	public String getItRegiStaff() {
		return this.itRegiStaff;
	}

	public void setItRegiStaff(String itRegiStaff) {
		this.itRegiStaff = itRegiStaff;
	}

/*	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_BAEK_IN_DT", length = 19)
	public Date getItBaekInDt() {
		return this.itBaekInDt;
	}*/

	public void setItBaekInDt(Date itBaekInDt) {
		this.itBaekInDt = itBaekInDt;
	}

	@Column(name = "IT_FACTORY_MEMO", length = 4000)
	public String getItFactoryMemo() {
		return this.itFactoryMemo;
	}

	public void setItFactoryMemo(String itFactoryMemo) {
		this.itFactoryMemo = itFactoryMemo;
	}
	//	이하 수정 혹은 추가 ------------------------------------------------------------------------
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_REQ_DT", nullable = false, length = 19)
	public Date getItReqDt() {
		return this.itReqDt;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_VISIT_DT", length = 19)
	public Date getItVisitDt() {
		return this.itVisitDt;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_IN_DT", length = 19)
	public Date getItInDt() {
		return this.itInDt;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_OUT_DT", length = 19)
	public Date getItOutDt() {
		return this.itOutDt;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_DELI_FU_VISIT_DT", length = 19)
	public Date getItDeliFuVisitDt() {
		return this.itDeliFuVisitDt;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_DELI_VISIT_DT", length = 19)
	public Date getItDeliVisitDt() {
		return this.itDeliVisitDt;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", nullable = false, length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IT_BAEK_IN_DT", length = 19)
	public Date getItBaekInDt() {
		return this.itBaekInDt;
	}

//	품목리스트 품목명칭 표시용
	@Transient
	public String getPdLvl() {
//		java.lang.String pdLvl = null;
		String pdLvl = null;

		if(this.pdLvl1 != null && this.pdLvl2 != null) pdLvl = this.pdLvl1.toString().concat(this.pdLvl2.toString());

		return pdLvl;
	}

	/**
	 *
	 [주문번호 조건]
	 년(2자리)+월(2자리)+일(2자리)+시(2자리)+분(2자리)+일련번호(4자리)
	 예) 1512071025000
	 */
/*	private String ORDER_NUMBER;

	@Transient
	public String getORDER_NUMBER() {
		String ordNum = null;

		if(this.id != null && this.id > 0) {
			DateFormat sdFormat = new SimpleDateFormat("yMMddkkmm");
			ordNum = sdFormat.format(this.regiDt);
		}

//		return ORDER_NUMBER;
		return ordNum;
	}*/

	//	신규/수정
	private String mode;

	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	//	가격(itPrice) + 추가요금(itAddChg)
	private Integer itTotPrice;

	@Transient
	public Integer getItTotPrice() {
		this.itTotPrice = this.itPrice;

/*//		if(this.itPrice != null && this.itPrice > 0) this.itTotPrice += this.itPrice;
		if(this.itAddChg != null && this.itAddChg > 0) this.itTotPrice += this.itAddChg;*/

		return itTotPrice;
	}

	private MultipartFile[] files;

	@Transient
	public MultipartFile[] getFiles() {
		return files;
	}

	public void setFiles(MultipartFile[] files) {
		this.files = files;
	}

	//	품목 상/중/하 6자리(코디 api 사용)
	private String pdAllLvl;

	@Transient
	public String getPdAllLvl() {
		String tmpAllLvl = null;

		if(!StringUtils.isEmpty(this.pdLvl1) && !StringUtils.isEmpty(this.pdLvl2) && !StringUtils.isEmpty(this.pdLvl3)) {
			tmpAllLvl = this.pdLvl1 + this.pdLvl2 + this.pdLvl3;
		}

		return tmpAllLvl;
//		return pdAllLvl;
	}

	public void setPdAllLvl(String pdAllLvl) {
		this.pdAllLvl = pdAllLvl;
	}

	private String itReqAddr1;
	private String itReqAddr2;
	private String itReqLat;
	private String itReqLng;

	private String itDeliAddr1;
	private String itDeliAddr2;
	private String itDeliLat;
	private String itDeliLng;

	@Transient
	public String getItDeliLng() {
		return itDeliLng;
	}

	public void setItDeliLng(String itDeliLng) {
		this.itDeliLng = itDeliLng;
	}

	@Transient
	public String getItReqLat() {
		return itReqLat;
	}

	public void setItReqLat(String itReqLat) {
		this.itReqLat = itReqLat;
	}

	@Transient
	public String getItReqLng() {
		return itReqLng;
	}

	public void setItReqLng(String itReqLng) {
		this.itReqLng = itReqLng;
	}

	@Transient
	public String getItDeliLat() {
		return itDeliLat;
	}

	public void setItDeliLat(String itDeliLat) {
		this.itDeliLat = itDeliLat;
	}

	List<TbPicture> pictures;

	@Transient
	public List<TbPicture> getPictures() {
		return pictures;
	}

	public void setPictures(List<TbPicture> pictures) {
		this.pictures = pictures;
	}

	@Transient
	public String getItReqAddr1() {
		return itReqAddr1;
	}

	public void setItReqAddr1(String itReqAddr1) {
		this.itReqAddr1 = itReqAddr1;
	}

	@Transient
	public String getItReqAddr2() {
		return itReqAddr2;
	}

	public void setItReqAddr2(String itReqAddr2) {
		this.itReqAddr2 = itReqAddr2;
	}

	@Transient
	public String getItDeliAddr1() {
		return itDeliAddr1;
	}

	public void setItDeliAddr1(String itDeliAddr1) {
		this.itDeliAddr1 = itDeliAddr1;
	}

	@Transient
	public String getItDeliAddr2() {
		return itDeliAddr2;
	}

	public void setItDeliAddr2(String itDeliAddr2) {
		this.itDeliAddr2 = itDeliAddr2;
	}

	//	시작 택번호
/*	@Transient
	private String bnBarCd;

	public String getBnBarCd() {
		return bnBarCd;
	}

	public void setBnBarCd(String bnBarCd) {
		this.bnBarCd = bnBarCd;
	}*/
}