package cleanbank.domain;

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbPartMember generated by hbm2java
 */
@Entity
@Table(name = "TB_PART_MEMBER", catalog = "cleanbank")
public class TbPartMember implements java.io.Serializable {

	private Integer id;
	private String delYn;
	private String evtNm;
	private String pmEmail;
	private String pmNm;
	private String pmPass;
	private String pmTel;
	private int ptCd;
	private Date regiDt;
	private String user;

	public TbPartMember() {
	}

	public TbPartMember(String delYn, String pmEmail, String pmNm, String pmPass, String pmTel, int ptCd, Date regiDt,
			String user) {
		this.delYn = delYn;
		this.pmEmail = pmEmail;
		this.pmNm = pmNm;
		this.pmPass = pmPass;
		this.pmTel = pmTel;
		this.ptCd = ptCd;
		this.regiDt = regiDt;
		this.user = user;
	}

	public TbPartMember(String delYn, String evtNm, String pmEmail, String pmNm, String pmPass, String pmTel, int ptCd,
			Date regiDt, String user) {
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.pmEmail = pmEmail;
		this.pmNm = pmNm;
		this.pmPass = pmPass;
		this.pmTel = pmTel;
		this.ptCd = ptCd;
		this.regiDt = regiDt;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "DEL_YN", nullable = false, length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "PM_EMAIL", nullable = false, length = 50)
	public String getPmEmail() {
		return this.pmEmail;
	}

	public void setPmEmail(String pmEmail) {
		this.pmEmail = pmEmail;
	}

	@Column(name = "PM_NM", nullable = false, length = 30)
	public String getPmNm() {
		return this.pmNm;
	}

	public void setPmNm(String pmNm) {
		this.pmNm = pmNm;
	}

	@Column(name = "PM_PASS", nullable = false, length = 100)
	public String getPmPass() {
		return this.pmPass;
	}

	public void setPmPass(String pmPass) {
		this.pmPass = pmPass;
	}

	@Column(name = "PM_TEL", nullable = false, length = 20)
	public String getPmTel() {
		return this.pmTel;
	}

	public void setPmTel(String pmTel) {
		this.pmTel = pmTel;
	}

	@Column(name = "PT_CD", nullable = false)
	public int getPtCd() {
		return this.ptCd;
	}

	public void setPtCd(int ptCd) {
		this.ptCd = ptCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", nullable = false, length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", nullable = false, length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	//	이하 수정 혹은 추가 ------------------------------------------------------------------------
	private String mode;
	private String newPass;

	//	신규/수정
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

//	수정시 비밀번호 변경
	@Transient
	public String getNewPass() {
		return newPass;
	}

	public void setNewPass(String newPass) {
		this.newPass = newPass;
	}
}
