package cleanbank.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbPicture generated by hbm2java
 */
@Entity
@Table(name = "TB_PICTURE", catalog = "cleanbank")
@JsonIgnoreProperties({"delYn", "evtNm", "itCd", "orCd", "ptCd", "ptImgFile", "regiDt", "user", "thumbnailFilename","newFilename","contentType","dateCreated","lastUpdated"})
public class TbPicture {

	private Integer id;
	private String delYn;
	private String evtNm;
	private long itCd;
	private long orCd;
	private long ptCd;
	private String ptImgFile;
	private Date regiDt;
	private String user;
	private String contentType;
	private Date dateCreated;
	private Date lastUpdated;
	private String name;
	private String newFilename;
	private Long size;
	private String thumbnailFilename;
	private Long thumbnailSize;

	public TbPicture() {
	}

	public TbPicture(long itCd, long orCd, long ptCd) {
		this.itCd = itCd;
		this.orCd = orCd;
		this.ptCd = ptCd;
	}

	public TbPicture(String delYn, String evtNm, long itCd, long orCd, long ptCd, String ptImgFile, Date regiDt,
					 String user, String contentType, Date dateCreated, Date lastUpdated, String name, String newFilename,
					 Long size, String thumbnailFilename, Long thumbnailSize) {
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.itCd = itCd;
		this.orCd = orCd;
		this.ptCd = ptCd;
		this.ptImgFile = ptImgFile;
		this.regiDt = regiDt;
		this.user = user;
		this.contentType = contentType;
		this.dateCreated = dateCreated;
		this.lastUpdated = lastUpdated;
		this.name = name;
		this.newFilename = newFilename;
		this.size = size;
		this.thumbnailFilename = thumbnailFilename;
		this.thumbnailSize = thumbnailSize;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "DEL_YN", length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "IT_CD", nullable = false)
	public long getItCd() {
		return this.itCd;
	}

	public void setItCd(long itCd) {
		this.itCd = itCd;
	}

	@Column(name = "OR_CD", nullable = false)
	public long getOrCd() {
		return this.orCd;
	}

	public void setOrCd(long orCd) {
		this.orCd = orCd;
	}

	@Column(name = "PT_CD", nullable = false)
	public long getPtCd() {
		return this.ptCd;
	}

	public void setPtCd(long ptCd) {
		this.ptCd = ptCd;
	}

	@Column(name = "PT_IMG_FILE", length = 200)
	public String getPtImgFile() {
		return this.ptImgFile;
	}

	public void setPtImgFile(String ptImgFile) {
		this.ptImgFile = ptImgFile;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "contentType")
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreated", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastUpdated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "newFilename")
	public String getNewFilename() {
		return this.newFilename;
	}

	public void setNewFilename(String newFilename) {
		this.newFilename = newFilename;
	}

	@Column(name = "size")
	public Long getSize() {
		return this.size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	@Column(name = "thumbnailFilename")
	public String getThumbnailFilename() {
		return this.thumbnailFilename;
	}

	public void setThumbnailFilename(String thumbnailFilename) {
		this.thumbnailFilename = thumbnailFilename;
	}

	@Column(name = "thumbnailSize")
	public Long getThumbnailSize() {
		return this.thumbnailSize;
	}

	public void setThumbnailSize(Long thumbnailSize) {
		this.thumbnailSize = thumbnailSize;
	}

	//	이하 수정 혹은 추가 ------------------------------------------------------------------------
	@Override
	public String toString() {
		return "Image{" + "name=" + name + ", thumbnailFilename=" + thumbnailFilename + ", newFilename=" + newFilename + ", contentType=" + contentType + ", url=" + url + ", thumbnailUrl=" + thumbnailUrl + ", deleteUrl=" + deleteUrl + ", deleteType=" + deleteType + '}';
	}

	private String url;
	private String thumbnailUrl;
	private String deleteUrl;
	private String deleteType;

	@Transient
	public String getDeleteType() {
//		return deleteType;
		return "DELETE";
	}

	public void setDeleteType(String deleteType) {
		this.deleteType = deleteType;
	}

	@Transient
	public String getUrl() {
//		return url;
		return "/file/picture/" + this.getId();
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Transient
	public String getThumbnailUrl() {
//		return thumbnailUrl;
		return "/file/thumbnail/" + this.getId();
	}

	public void setThumbnailUrl(String thumbnailUrl) {
		this.thumbnailUrl = thumbnailUrl;
	}

	@Transient
	public String getDeleteUrl() {
//		return deleteUrl;
		return "/file/delete/"+ this.getId();
	}

	public void setDeleteUrl(String deleteUrl) {
		this.deleteUrl = deleteUrl;
	}
}
