package cleanbank.domain;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbPromotion generated by hbm2java
 */
@Entity
@Table(name = "TB_PROMOTION", catalog = "cleanbank")
public class TbPromotion implements java.io.Serializable {

	private Long poCd;
	private String delYn;
	private String evtNm;
	private String poDesc;
	private String poDubYn;
	private Date poFinishDt;
	private Date poFinishTm;
	private Integer poGoldPer;
	private Integer poGoldPrice;
	private Integer poGreenPer;
	private Integer poGreenPrice;
	private String poImg;
	private String poNm;
	private Integer poSilverPer;
	private Integer poSilverPrice;
	private Date poStartDt;
	private Date poStartTm;
	private String poType;
	private Date regiDt;
	private String user;
	private String poMon;
	private String poTue;
	private String poWed;
	private String poThu;
	private String poFri;
	private String poSat;
	private String poSun;
	private String poPushMsg;
	private String poCoup;
	private Integer poCoupPubCnt;
	private Integer poLimitAmount;
	private Integer poDiscountAmt;

	public TbPromotion() {
	}

	public TbPromotion(String delYn, String evtNm, String poDesc, String poDubYn, Date poFinishDt, Date poFinishTm,
					   Integer poGoldPer, Integer poGoldPrice, Integer poGreenPer, Integer poGreenPrice, String poImg, String poNm,
					   Integer poSilverPer, Integer poSilverPrice, Date poStartDt, Date poStartTm, String poType, Date regiDt,
					   String user, String poMon, String poTue, String poWed, String poThu, String poFri, String poSat,
					   String poSun, String poPushMsg, String poCoup, Integer poCoupPubCnt, Integer poLimitAmount,
					   Integer poDiscountAmt) {
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.poDesc = poDesc;
		this.poDubYn = poDubYn;
		this.poFinishDt = poFinishDt;
		this.poFinishTm = poFinishTm;
		this.poGoldPer = poGoldPer;
		this.poGoldPrice = poGoldPrice;
		this.poGreenPer = poGreenPer;
		this.poGreenPrice = poGreenPrice;
		this.poImg = poImg;
		this.poNm = poNm;
		this.poSilverPer = poSilverPer;
		this.poSilverPrice = poSilverPrice;
		this.poStartDt = poStartDt;
		this.poStartTm = poStartTm;
		this.poType = poType;
		this.regiDt = regiDt;
		this.user = user;
		this.poMon = poMon;
		this.poTue = poTue;
		this.poWed = poWed;
		this.poThu = poThu;
		this.poFri = poFri;
		this.poSat = poSat;
		this.poSun = poSun;
		this.poPushMsg = poPushMsg;
		this.poCoup = poCoup;
		this.poCoupPubCnt = poCoupPubCnt;
		this.poLimitAmount = poLimitAmount;
		this.poDiscountAmt = poDiscountAmt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PO_CD", unique = true, nullable = false)
	public Long getPoCd() {
		return this.poCd;
	}

	public void setPoCd(Long poCd) {
		this.poCd = poCd;
	}

	@Column(name = "DEL_YN", length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "PO_DESC", length = 200)
	public String getPoDesc() {
		return this.poDesc;
	}

	public void setPoDesc(String poDesc) {
		this.poDesc = poDesc;
	}

	@Column(name = "PO_DUB_YN", length = 4)
	public String getPoDubYn() {
		return this.poDubYn;
	}

	public void setPoDubYn(String poDubYn) {
		this.poDubYn = poDubYn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PO_FINISH_DT", length = 19)
	public Date getPoFinishDt() {
		return this.poFinishDt;
	}

	public void setPoFinishDt(Date poFinishDt) {
		this.poFinishDt = poFinishDt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "PO_FINISH_TM", length = 8)
	public Date getPoFinishTm() {
		return this.poFinishTm;
	}

	public void setPoFinishTm(Date poFinishTm) {
		this.poFinishTm = poFinishTm;
	}

	@Column(name = "PO_GOLD_PER")
	public Integer getPoGoldPer() {
		return this.poGoldPer;
	}

	public void setPoGoldPer(Integer poGoldPer) {
		this.poGoldPer = poGoldPer;
	}

	@Column(name = "PO_GOLD_PRICE")
	public Integer getPoGoldPrice() {
		return this.poGoldPrice;
	}

	public void setPoGoldPrice(Integer poGoldPrice) {
		this.poGoldPrice = poGoldPrice;
	}

	@Column(name = "PO_GREEN_PER")
	public Integer getPoGreenPer() {
		return this.poGreenPer;
	}

	public void setPoGreenPer(Integer poGreenPer) {
		this.poGreenPer = poGreenPer;
	}

	@Column(name = "PO_GREEN_PRICE")
	public Integer getPoGreenPrice() {
		return this.poGreenPrice;
	}

	public void setPoGreenPrice(Integer poGreenPrice) {
		this.poGreenPrice = poGreenPrice;
	}

	@Column(name = "PO_IMG", length = 400)
	public String getPoImg() {
		return this.poImg;
	}

	public void setPoImg(String poImg) {
		this.poImg = poImg;
	}

	@Column(name = "PO_NM", length = 100)
	public String getPoNm() {
		return this.poNm;
	}

	public void setPoNm(String poNm) {
		this.poNm = poNm;
	}

	@Column(name = "PO_SILVER_PER")
	public Integer getPoSilverPer() {
		return this.poSilverPer;
	}

	public void setPoSilverPer(Integer poSilverPer) {
		this.poSilverPer = poSilverPer;
	}

	@Column(name = "PO_SILVER_PRICE")
	public Integer getPoSilverPrice() {
		return this.poSilverPrice;
	}

	public void setPoSilverPrice(Integer poSilverPrice) {
		this.poSilverPrice = poSilverPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PO_START_DT", length = 19)
	public Date getPoStartDt() {
		return this.poStartDt;
	}

	public void setPoStartDt(Date poStartDt) {
		this.poStartDt = poStartDt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "PO_START_TM", length = 8)
	public Date getPoStartTm() {
		return this.poStartTm;
	}

	public void setPoStartTm(Date poStartTm) {
		this.poStartTm = poStartTm;
	}

	@Column(name = "PO_TYPE", length = 4)
	public String getPoType() {
		return this.poType;
	}

	public void setPoType(String poType) {
		this.poType = poType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@Column(name = "USER", length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "PO_MON", length = 1)
	public String getPoMon() {
		return this.poMon;
	}

	public void setPoMon(String poMon) {
		this.poMon = poMon;
	}

	@Column(name = "PO_TUE", length = 1)
	public String getPoTue() {
		return this.poTue;
	}

	public void setPoTue(String poTue) {
		this.poTue = poTue;
	}

	@Column(name = "PO_WED", length = 1)
	public String getPoWed() {
		return this.poWed;
	}

	public void setPoWed(String poWed) {
		this.poWed = poWed;
	}

	@Column(name = "PO_THU", length = 1)
	public String getPoThu() {
		return this.poThu;
	}

	public void setPoThu(String poThu) {
		this.poThu = poThu;
	}

	@Column(name = "PO_FRI", length = 1)
	public String getPoFri() {
		return this.poFri;
	}

	public void setPoFri(String poFri) {
		this.poFri = poFri;
	}

	@Column(name = "PO_SAT", length = 1)
	public String getPoSat() {
		return this.poSat;
	}

	public void setPoSat(String poSat) {
		this.poSat = poSat;
	}

	@Column(name = "PO_SUN", length = 1)
	public String getPoSun() {
		return this.poSun;
	}

	public void setPoSun(String poSun) {
		this.poSun = poSun;
	}

	@Column(name = "PO_PUSH_MSG", length = 1)
	public String getPoPushMsg() {
		return this.poPushMsg;
	}

	public void setPoPushMsg(String poPushMsg) {
		this.poPushMsg = poPushMsg;
	}

	@Column(name = "PO_COUP", length = 12)
	public String getPoCoup() {
		return this.poCoup;
	}

	public void setPoCoup(String poCoup) {
		this.poCoup = poCoup;
	}

	@Column(name = "PO_COUP_PUB_CNT")
	public Integer getPoCoupPubCnt() {
		return this.poCoupPubCnt;
	}

	public void setPoCoupPubCnt(Integer poCoupPubCnt) {
		this.poCoupPubCnt = poCoupPubCnt;
	}

	@Column(name = "PO_LIMIT_AMOUNT")
	public Integer getPoLimitAmount() {
		return this.poLimitAmount;
	}

	public void setPoLimitAmount(Integer poLimitAmount) {
		this.poLimitAmount = poLimitAmount;
	}

	@Column(name = "PO_DISCOUNT_AMT")
	public Integer getPoDiscountAmt() {
		return this.poDiscountAmt;
	}

	public void setPoDiscountAmt(Integer poDiscountAmt) {
		this.poDiscountAmt = poDiscountAmt;
	}

	//	이하 수정 혹은 추가 ------------------------------------------------------------------------
	private String mode;

	//	신규/수정
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}
/*
//	프로모션시작시간(시)
	private String poStartTm1;

	@Transient
	public String getPoStartTm1() {
		String tempDate = this.poStartTm1;

		if(this.poStartTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("HH");
			tempDate = sdFormat.format(this.poStartTm);
		}

		return tempDate;
	}

	public void setPoStartTm1(String poStartTm1) {
		this.poStartTm1 = poStartTm1;
	}

	//	프로모션시작시간(분)
	private String poStartTm2;

	@Transient
	public String getPoStartTm2() {
		String tempDate = this.poStartTm1;

		if(this.poStartTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("mm");
			tempDate = sdFormat.format(this.poStartTm);
		}

		return tempDate;
	}

	public void setPoStartTm2(String poStartTm2) {
		this.poStartTm2 = poStartTm2;
	}

	//	프로모션종료시간(시)
	private String poFinishTm1;

	@Transient
	public String getpoFinishTm1() {
		String tempDate = this.poFinishTm1;

		if(this.poFinishTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("HH");
			tempDate = sdFormat.format(this.poFinishTm);
		}

		return tempDate;
	}

	public void setpoFinishTm1(String poFinishTm1) {
		this.poFinishTm1 = poFinishTm1;
	}

	//	프로모션종료시간(분)
	private String poFinishTm2;

	@Transient
	public String getpoFinishTm2() {
		String tempDate = this.poFinishTm1;

		if(this.poFinishTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("mm");
			tempDate = sdFormat.format(this.poFinishTm);
		}

		return tempDate;
	}

	public void setpoFinishTm2(String poFinishTm2) {
		this.poFinishTm2 = poFinishTm2;
	}*/

	//	프로모션 기간 그리드 검색용
	private String poDt;

	@Transient
	public String getPoDt() {
		String tempDate = "";
		DateFormat sdFormat = new SimpleDateFormat("yyyy-MM-dd");

		if(this.poStartDt != null) {
			tempDate = sdFormat.format(this.poStartDt);
		}

		tempDate += " ~ ";

		if(this.poFinishDt != null) {
			tempDate += sdFormat.format(this.poFinishDt);
		}

		return tempDate;
	}

//	해당 쿠폰의 사용수량
	private Integer poCoupUseCnt;

	@Transient
	public Integer getPoCoupUseCnt() {
		return poCoupUseCnt;
	}

	public void setPoCoupUseCnt(Integer poCoupUseCnt) {
		this.poCoupUseCnt = poCoupUseCnt;
	}

	/*public void setPoDt(String poDt) {
		this.poDt = poDt;
	}*/

//	프로모션 시작시간
	private String poStartTm0;

	@Transient
	public String getPoStartTm0() {
//		return poStartTm0;
		String tempDate = this.poStartTm0;

		if(this.poStartTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("HH:mm");
			tempDate = sdFormat.format(this.poStartTm);
		}

		return tempDate;
	}

	public void setPoStartTm0(String poStartTm0) {
		this.poStartTm0 = poStartTm0;
	}

	private String poFinishTm0;

	@Transient
	public String getPoFinishTm0() {
//		return poFinishTm0;
		String tempDate = this.poFinishTm0;

		if(this.poFinishTm != null) {
			DateFormat sdFormat = new SimpleDateFormat("HH:mm");
			tempDate = sdFormat.format(this.poFinishTm);
		}

		return tempDate;
	}

	public void setPoFinishTm0(String poFinishTm0) {
		this.poFinishTm0 = poFinishTm0;
	}

	private Date poFinishDtTm;

	@Transient
	public Date getPoFinishDtTm() throws ParseException {
		DateFormat df4 = new SimpleDateFormat("yyyyMMdd");
		DateFormat df5 = new SimpleDateFormat("HHmm");
		DateFormat df6 = new SimpleDateFormat("yyyyMMddHHmm");

		Date tmpDt = this.poFinishDt;
		Date tmpTm = this.poFinishTm;

		if(poFinishDt != null && tmpTm != null) tmpDt = df6.parse(df4.format(tmpDt) + df5.format(tmpTm));

		return tmpDt;
	}

	public void setPoFinishDtTm(Date poFinishDtTm) {
		this.poFinishDtTm = poFinishDtTm;
	}
}