package cleanbank.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbProduct generated by hbm2java
 */
@Entity
@Table(name = "TB_PRODUCT", catalog = "cleanbank")
public class TbProduct implements java.io.Serializable {

	private Integer id;
	private String delYn;
	private String evtNm;
	private String pdDesc;
	private String pdLvl1;
	private String pdLvl2;
	private String pdLvl3;
	private String pdNm;
	private Integer pdPrice;
	private Integer pdSort;
	private Date regiDt;
	private String user;
	private Integer pdPer;

	public TbProduct() {
	}

	public TbProduct(String pdLvl1, String pdLvl2, String pdLvl3) {
		this.pdLvl1 = pdLvl1;
		this.pdLvl2 = pdLvl2;
		this.pdLvl3 = pdLvl3;
	}

	public TbProduct(String delYn, String evtNm, String pdDesc, String pdLvl1, String pdLvl2, String pdLvl3,
					 String pdNm, Integer pdPrice, Integer pdSort, Date regiDt, String user, Integer pdPer) {
		this.delYn = delYn;
		this.evtNm = evtNm;
		this.pdDesc = pdDesc;
		this.pdLvl1 = pdLvl1;
		this.pdLvl2 = pdLvl2;
		this.pdLvl3 = pdLvl3;
		this.pdNm = pdNm;
		this.pdPrice = pdPrice;
		this.pdSort = pdSort;
		this.regiDt = regiDt;
		this.user = user;
		this.pdPer = pdPer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	@Column(name = "DEL_YN", length = 1)
	public String getDelYn() {
		return this.delYn;
	}

	public void setDelYn(String delYn) {
		this.delYn = delYn;
	}

	@JsonIgnore
	@Column(name = "EVT_NM", length = 30)
	public String getEvtNm() {
		return this.evtNm;
	}

	public void setEvtNm(String evtNm) {
		this.evtNm = evtNm;
	}

	@Column(name = "PD_DESC", length = 100)
	public String getPdDesc() {
		return this.pdDesc;
	}

	public void setPdDesc(String pdDesc) {
		this.pdDesc = pdDesc;
	}

	@Column(name = "PD_LVL1", nullable = false, length = 2)
	public String getPdLvl1() {
		return this.pdLvl1;
	}

	public void setPdLvl1(String pdLvl1) {
		this.pdLvl1 = pdLvl1;
	}

	@Column(name = "PD_LVL2", nullable = false, length = 2)
	public String getPdLvl2() {
		return this.pdLvl2;
	}

	public void setPdLvl2(String pdLvl2) {
		this.pdLvl2 = pdLvl2;
	}

	@Column(name = "PD_LVL3", nullable = false, length = 2)
	public String getPdLvl3() {
		return this.pdLvl3;
	}

	public void setPdLvl3(String pdLvl3) {
		this.pdLvl3 = pdLvl3;
	}

	@Column(name = "PD_NM", length = 100)
	public String getPdNm() {
		return this.pdNm;
	}

	public void setPdNm(String pdNm) {
		this.pdNm = pdNm;
	}

	public void setPdPrice(Integer pdPrice) {
		this.pdPrice = pdPrice;
	}

	@Column(name = "PD_SORT")
	public Integer getPdSort() {
		return this.pdSort;
	}

	public void setPdSort(Integer pdSort) {
		this.pdSort = pdSort;
	}

	@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGI_DT", length = 19)
	public Date getRegiDt() {
		return this.regiDt;
	}

	public void setRegiDt(Date regiDt) {
		this.regiDt = regiDt;
	}

	@JsonIgnore
	@Column(name = "USER")
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "PD_PER")
	public Integer getPdPer() {
		return this.pdPer;
	}

	public void setPdPer(Integer pdPer) {
		this.pdPer = pdPer;
	}

	//	이하 수정 혹은 추가 ------------------------------------------------------------------------
	@JsonFormat(shape=JsonFormat.Shape.NUMBER_INT)
	@Column(name = "PD_PRICE")
	public Integer getPdPrice() {
		return this.pdPrice;
	}

	private String mode;

	//	신규/수정
	@JsonIgnore
	@Transient
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}
}
