package cleanbank.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPushHistory generated by hbm2java
 */
@Entity
@Table(name = "TB_PUSH_HISTORY", catalog = "cleanbank")
public class TbPushHistory implements java.io.Serializable {

	private Integer id;
	private String pushTitle;
	private Date regDt;
	private int mbCd;

	public TbPushHistory() {
	}

	public TbPushHistory(String pushTitle, Date regDt, int mbCd) {
		this.pushTitle = pushTitle;
		this.regDt = regDt;
		this.mbCd = mbCd;
	}

	@JsonIgnore
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PUSH_TITLE", nullable = false, length = 200)
	public String getPushTitle() {
		return this.pushTitle;
	}

	public void setPushTitle(String pushTitle) {
		this.pushTitle = pushTitle;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm", timezone="Asia/Seoul")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REG_DT", nullable = false, length = 19)
	public Date getRegDt() {
		return this.regDt;
	}

	public void setRegDt(Date regDt) {
		this.regDt = regDt;
	}

	@Column(name = "MB_CD", nullable = false)
	public int getMbCd() {
		return this.mbCd;
	}

	public void setMbCd(int mbCd) {
		this.mbCd = mbCd;
	}

}
